spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

spring.config.activate.on-profile: dev_hgcx
file:
  upload-path: D:\easy-git\image
  #파일 업로드 가능 확장자
  extn: jpg,gif,bmp,png
  file-extns: jpg,jpeg,gif,png,bmp,mp4,wmv,avi,mkv,pdf,ppt,pptx,xls,xlsx,doc,docx,dox,hwp,txt,zip
  image-extns: jpg,jpeg,gif,png,bmp
  video-extns: mp4,wmv,avi,mkv
  document-extns: pdf,ppt,pptx,xls,xlsx,doc,docx,hwp,txt
  etc-extns: zip
  mnVsl-extns: jpg, png, gif, mp4, webm
  pop-extns: jpg, png, gif
  news-extns: jpg, png, gif
  comm-extns: jpg, png, gif
  ntfy-extns: pdf, docx, xlsx, zip, jpg
  #파일 업로드 크기
  max-size: 10485760
---
spring.config.activate.on-profile: stg_hgcx
file:
  upload-path: D:\easy-git\image
  #파일 업로드 가능 확장자
  extn: jpg,gif,bmp,png
  file-extns: jpg,jpeg,gif,png,bmp,mp4,wmv,avi,mkv,pdf,ppt,pptx,xls,xlsx,doc,docx,dox,hwp,txt,zip
  image-extns: jpg,jpeg,gif,png,bmp
  video-extns: mp4,wmv,avi,mkv
  document-extns: pdf,ppt,pptx,xls,xlsx,doc,docx,hwp,txt
  etc-extns: zip
  mnVsl-extns: jpg, png, gif, mp4, webm
  pop-extns: jpg, png, gif
  news-extns: jpg, png, gif
  comm-extns: jpg, png, gif
  ntfy-extns: pdf, docx, xlsx, zip, jpg
  #파일 업로드 크기
  max-size: 10485760
---
spring.config.activate.on-profile: prod_hgcx
file:
  upload-path: D:\easy-git\image
  #파일 업로드 가능 확장자
  extn: jpg,gif,bmp,png
  file-extns: jpg,jpeg,gif,png,bmp,mp4,wmv,avi,mkv,pdf,ppt,pptx,xls,xlsx,doc,docx,dox,hwp,txt,zip
  image-extns: jpg,jpeg,gif,png,bmp
  video-extns: mp4,wmv,avi,mkv
  document-extns: pdf,ppt,pptx,xls,xlsx,doc,docx,hwp,txt
  etc-extns: zip
  mnVsl-extns: jpg, png, gif, mp4, webm
  pop-extns: jpg, png, gif
  news-extns: jpg, png, gif
  comm-extns: jpg, png, gif
  ntfy-extns: pdf, docx, xlsx, zip, jpg
  #파일 업로드 크기
  max-size: 10485760